//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFJM.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnameField;
        
        private int UageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Uname {
            get {
                return this.UnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UnameField, value) != true)) {
                    this.UnameField = value;
                    this.RaisePropertyChanged("Uname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Uage {
            get {
                return this.UageField;
            }
            set {
                if ((this.UageField.Equals(value) != true)) {
                    this.UageField = value;
                    this.RaisePropertyChanged("Uage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Usex {
            get {
                return this.UsexField;
            }
            set {
                if ((object.ReferenceEquals(this.UsexField, value) != true)) {
                    this.UsexField = value;
                    this.RaisePropertyChanged("Usex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Udate {
            get {
                return this.UdateField;
            }
            set {
                if ((object.ReferenceEquals(this.UdateField, value) != true)) {
                    this.UdateField = value;
                    this.RaisePropertyChanged("Udate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DintroductionField;
        
        private int DappearanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DID {
            get {
                return this.DIDField;
            }
            set {
                if ((this.DIDField.Equals(value) != true)) {
                    this.DIDField = value;
                    this.RaisePropertyChanged("DID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Dname {
            get {
                return this.DnameField;
            }
            set {
                if ((object.ReferenceEquals(this.DnameField, value) != true)) {
                    this.DnameField = value;
                    this.RaisePropertyChanged("Dname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dintroduction {
            get {
                return this.DintroductionField;
            }
            set {
                if ((object.ReferenceEquals(this.DintroductionField, value) != true)) {
                    this.DintroductionField = value;
                    this.RaisePropertyChanged("Dintroduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Dappearance {
            get {
                return this.DappearanceField;
            }
            set {
                if ((this.DappearanceField.Equals(value) != true)) {
                    this.DappearanceField = value;
                    this.RaisePropertyChanged("Dappearance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ChatIDField;
        
        private int DIDField;
        
        private int UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ChatID {
            get {
                return this.ChatIDField;
            }
            set {
                if ((this.ChatIDField.Equals(value) != true)) {
                    this.ChatIDField = value;
                    this.RaisePropertyChanged("ChatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DID {
            get {
                return this.DIDField;
            }
            set {
                if ((this.DIDField.Equals(value) != true)) {
                    this.DIDField = value;
                    this.RaisePropertyChanged("DID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WPFJM.ServiceReference1.HelloWorldResponse HelloWorld(WPFJM.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Uname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUserDetails", ReplyAction="*")]
        WPFJM.ServiceReference1.InsertUserDetailsResponse InsertUserDetails(WPFJM.ServiceReference1.InsertUserDetailsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllUserResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUser", ReplyAction="*")]
        WPFJM.ServiceReference1.GetAllUserResponse GetAllUser(WPFJM.ServiceReference1.GetAllUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 searchstring 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUser", ReplyAction="*")]
        WPFJM.ServiceReference1.FindUserResponse FindUser(WPFJM.ServiceReference1.FindUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 searchstring 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUID", ReplyAction="*")]
        WPFJM.ServiceReference1.FindUIDResponse FindUID(WPFJM.ServiceReference1.FindUIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Dname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDeviceDetails", ReplyAction="*")]
        WPFJM.ServiceReference1.InsertDeviceDetailsResponse InsertDeviceDetails(WPFJM.ServiceReference1.InsertDeviceDetailsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 searchstring 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDevice", ReplyAction="*")]
        WPFJM.ServiceReference1.FindDeviceResponse FindDevice(WPFJM.ServiceReference1.FindDeviceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllDeviceResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDevice", ReplyAction="*")]
        WPFJM.ServiceReference1.GetAllDeviceResponse GetAllDevice(WPFJM.ServiceReference1.GetAllDeviceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 searchstring 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindChatByUID", ReplyAction="*")]
        WPFJM.ServiceReference1.FindChatByUIDResponse FindChatByUID(WPFJM.ServiceReference1.FindChatByUIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 searchstring 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindChatByDID", ReplyAction="*")]
        WPFJM.ServiceReference1.FindChatByDIDResponse FindChatByDID(WPFJM.ServiceReference1.FindChatByDIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Comment 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertChatDetails", ReplyAction="*")]
        WPFJM.ServiceReference1.InsertChatDetailsResponse InsertChatDetails(WPFJM.ServiceReference1.InsertChatDetailsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllChatResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllChat", ReplyAction="*")]
        WPFJM.ServiceReference1.GetAllChatResponse GetAllChat(WPFJM.ServiceReference1.GetAllChatRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WPFJM.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WPFJM.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertUserDetails", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.InsertUserDetailsRequestBody Body;
        
        public InsertUserDetailsRequest() {
        }
        
        public InsertUserDetailsRequest(WPFJM.ServiceReference1.InsertUserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertUserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Uname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Uage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Usex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Udate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public InsertUserDetailsRequestBody() {
        }
        
        public InsertUserDetailsRequestBody(int UID, string Uname, int Uage, string Usex, string Udate, string Password) {
            this.UID = UID;
            this.Uname = Uname;
            this.Uage = Uage;
            this.Usex = Usex;
            this.Udate = Udate;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertUserDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.InsertUserDetailsResponseBody Body;
        
        public InsertUserDetailsResponse() {
        }
        
        public InsertUserDetailsResponse(WPFJM.ServiceReference1.InsertUserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertUserDetailsResponseBody {
        
        public InsertUserDetailsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUser", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.GetAllUserRequestBody Body;
        
        public GetAllUserRequest() {
        }
        
        public GetAllUserRequest(WPFJM.ServiceReference1.GetAllUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUserRequestBody {
        
        public GetAllUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.GetAllUserResponseBody Body;
        
        public GetAllUserResponse() {
        }
        
        public GetAllUserResponse(WPFJM.ServiceReference1.GetAllUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.User[] GetAllUserResult;
        
        public GetAllUserResponseBody() {
        }
        
        public GetAllUserResponseBody(WPFJM.ServiceReference1.User[] GetAllUserResult) {
            this.GetAllUserResult = GetAllUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindUser", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindUserRequestBody Body;
        
        public FindUserRequest() {
        }
        
        public FindUserRequest(WPFJM.ServiceReference1.FindUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchstring;
        
        public FindUserRequestBody() {
        }
        
        public FindUserRequestBody(string searchstring) {
            this.searchstring = searchstring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindUserResponseBody Body;
        
        public FindUserResponse() {
        }
        
        public FindUserResponse(WPFJM.ServiceReference1.FindUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.User[] FindUserResult;
        
        public FindUserResponseBody() {
        }
        
        public FindUserResponseBody(WPFJM.ServiceReference1.User[] FindUserResult) {
            this.FindUserResult = FindUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindUID", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindUIDRequestBody Body;
        
        public FindUIDRequest() {
        }
        
        public FindUIDRequest(WPFJM.ServiceReference1.FindUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchstring;
        
        public FindUIDRequestBody() {
        }
        
        public FindUIDRequestBody(string searchstring) {
            this.searchstring = searchstring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindUIDResponseBody Body;
        
        public FindUIDResponse() {
        }
        
        public FindUIDResponse(WPFJM.ServiceReference1.FindUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.User FindUIDResult;
        
        public FindUIDResponseBody() {
        }
        
        public FindUIDResponseBody(WPFJM.ServiceReference1.User FindUIDResult) {
            this.FindUIDResult = FindUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDeviceDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDeviceDetails", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.InsertDeviceDetailsRequestBody Body;
        
        public InsertDeviceDetailsRequest() {
        }
        
        public InsertDeviceDetailsRequest(WPFJM.ServiceReference1.InsertDeviceDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDeviceDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Dname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dintroduction;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Dappearance;
        
        public InsertDeviceDetailsRequestBody() {
        }
        
        public InsertDeviceDetailsRequestBody(int DID, string Dname, string Dintroduction, int Dappearance) {
            this.DID = DID;
            this.Dname = Dname;
            this.Dintroduction = Dintroduction;
            this.Dappearance = Dappearance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDeviceDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDeviceDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.InsertDeviceDetailsResponseBody Body;
        
        public InsertDeviceDetailsResponse() {
        }
        
        public InsertDeviceDetailsResponse(WPFJM.ServiceReference1.InsertDeviceDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertDeviceDetailsResponseBody {
        
        public InsertDeviceDetailsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDevice", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindDeviceRequestBody Body;
        
        public FindDeviceRequest() {
        }
        
        public FindDeviceRequest(WPFJM.ServiceReference1.FindDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDeviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchstring;
        
        public FindDeviceRequestBody() {
        }
        
        public FindDeviceRequestBody(string searchstring) {
            this.searchstring = searchstring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDeviceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindDeviceResponseBody Body;
        
        public FindDeviceResponse() {
        }
        
        public FindDeviceResponse(WPFJM.ServiceReference1.FindDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.Device[] FindDeviceResult;
        
        public FindDeviceResponseBody() {
        }
        
        public FindDeviceResponseBody(WPFJM.ServiceReference1.Device[] FindDeviceResult) {
            this.FindDeviceResult = FindDeviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDevice", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.GetAllDeviceRequestBody Body;
        
        public GetAllDeviceRequest() {
        }
        
        public GetAllDeviceRequest(WPFJM.ServiceReference1.GetAllDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDeviceRequestBody {
        
        public GetAllDeviceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDeviceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.GetAllDeviceResponseBody Body;
        
        public GetAllDeviceResponse() {
        }
        
        public GetAllDeviceResponse(WPFJM.ServiceReference1.GetAllDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.Device[] GetAllDeviceResult;
        
        public GetAllDeviceResponseBody() {
        }
        
        public GetAllDeviceResponseBody(WPFJM.ServiceReference1.Device[] GetAllDeviceResult) {
            this.GetAllDeviceResult = GetAllDeviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindChatByUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindChatByUID", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindChatByUIDRequestBody Body;
        
        public FindChatByUIDRequest() {
        }
        
        public FindChatByUIDRequest(WPFJM.ServiceReference1.FindChatByUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindChatByUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchstring;
        
        public FindChatByUIDRequestBody() {
        }
        
        public FindChatByUIDRequestBody(string searchstring) {
            this.searchstring = searchstring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindChatByUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindChatByUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindChatByUIDResponseBody Body;
        
        public FindChatByUIDResponse() {
        }
        
        public FindChatByUIDResponse(WPFJM.ServiceReference1.FindChatByUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindChatByUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.Chat[] FindChatByUIDResult;
        
        public FindChatByUIDResponseBody() {
        }
        
        public FindChatByUIDResponseBody(WPFJM.ServiceReference1.Chat[] FindChatByUIDResult) {
            this.FindChatByUIDResult = FindChatByUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindChatByDIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindChatByDID", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindChatByDIDRequestBody Body;
        
        public FindChatByDIDRequest() {
        }
        
        public FindChatByDIDRequest(WPFJM.ServiceReference1.FindChatByDIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindChatByDIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchstring;
        
        public FindChatByDIDRequestBody() {
        }
        
        public FindChatByDIDRequestBody(string searchstring) {
            this.searchstring = searchstring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindChatByDIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindChatByDIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.FindChatByDIDResponseBody Body;
        
        public FindChatByDIDResponse() {
        }
        
        public FindChatByDIDResponse(WPFJM.ServiceReference1.FindChatByDIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindChatByDIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.Chat[] FindChatByDIDResult;
        
        public FindChatByDIDResponseBody() {
        }
        
        public FindChatByDIDResponseBody(WPFJM.ServiceReference1.Chat[] FindChatByDIDResult) {
            this.FindChatByDIDResult = FindChatByDIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertChatDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertChatDetails", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.InsertChatDetailsRequestBody Body;
        
        public InsertChatDetailsRequest() {
        }
        
        public InsertChatDetailsRequest(WPFJM.ServiceReference1.InsertChatDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertChatDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChatID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int UID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Comment;
        
        public InsertChatDetailsRequestBody() {
        }
        
        public InsertChatDetailsRequestBody(int ChatID, int DID, int UID, string Comment) {
            this.ChatID = ChatID;
            this.DID = DID;
            this.UID = UID;
            this.Comment = Comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertChatDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertChatDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.InsertChatDetailsResponseBody Body;
        
        public InsertChatDetailsResponse() {
        }
        
        public InsertChatDetailsResponse(WPFJM.ServiceReference1.InsertChatDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertChatDetailsResponseBody {
        
        public InsertChatDetailsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllChatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllChat", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.GetAllChatRequestBody Body;
        
        public GetAllChatRequest() {
        }
        
        public GetAllChatRequest(WPFJM.ServiceReference1.GetAllChatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllChatRequestBody {
        
        public GetAllChatRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllChatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllChatResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPFJM.ServiceReference1.GetAllChatResponseBody Body;
        
        public GetAllChatResponse() {
        }
        
        public GetAllChatResponse(WPFJM.ServiceReference1.GetAllChatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllChatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPFJM.ServiceReference1.Chat[] GetAllChatResult;
        
        public GetAllChatResponseBody() {
        }
        
        public GetAllChatResponseBody(WPFJM.ServiceReference1.Chat[] GetAllChatResult) {
            this.GetAllChatResult = GetAllChatResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WPFJM.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WPFJM.ServiceReference1.Service1Soap>, WPFJM.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.HelloWorldResponse WPFJM.ServiceReference1.Service1Soap.HelloWorld(WPFJM.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WPFJM.ServiceReference1.HelloWorldRequest inValue = new WPFJM.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WPFJM.ServiceReference1.HelloWorldRequestBody();
            WPFJM.ServiceReference1.HelloWorldResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.InsertUserDetailsResponse WPFJM.ServiceReference1.Service1Soap.InsertUserDetails(WPFJM.ServiceReference1.InsertUserDetailsRequest request) {
            return base.Channel.InsertUserDetails(request);
        }
        
        public void InsertUserDetails(int UID, string Uname, int Uage, string Usex, string Udate, string Password) {
            WPFJM.ServiceReference1.InsertUserDetailsRequest inValue = new WPFJM.ServiceReference1.InsertUserDetailsRequest();
            inValue.Body = new WPFJM.ServiceReference1.InsertUserDetailsRequestBody();
            inValue.Body.UID = UID;
            inValue.Body.Uname = Uname;
            inValue.Body.Uage = Uage;
            inValue.Body.Usex = Usex;
            inValue.Body.Udate = Udate;
            inValue.Body.Password = Password;
            WPFJM.ServiceReference1.InsertUserDetailsResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).InsertUserDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.GetAllUserResponse WPFJM.ServiceReference1.Service1Soap.GetAllUser(WPFJM.ServiceReference1.GetAllUserRequest request) {
            return base.Channel.GetAllUser(request);
        }
        
        public WPFJM.ServiceReference1.User[] GetAllUser() {
            WPFJM.ServiceReference1.GetAllUserRequest inValue = new WPFJM.ServiceReference1.GetAllUserRequest();
            inValue.Body = new WPFJM.ServiceReference1.GetAllUserRequestBody();
            WPFJM.ServiceReference1.GetAllUserResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).GetAllUser(inValue);
            return retVal.Body.GetAllUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.FindUserResponse WPFJM.ServiceReference1.Service1Soap.FindUser(WPFJM.ServiceReference1.FindUserRequest request) {
            return base.Channel.FindUser(request);
        }
        
        public WPFJM.ServiceReference1.User[] FindUser(string searchstring) {
            WPFJM.ServiceReference1.FindUserRequest inValue = new WPFJM.ServiceReference1.FindUserRequest();
            inValue.Body = new WPFJM.ServiceReference1.FindUserRequestBody();
            inValue.Body.searchstring = searchstring;
            WPFJM.ServiceReference1.FindUserResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).FindUser(inValue);
            return retVal.Body.FindUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.FindUIDResponse WPFJM.ServiceReference1.Service1Soap.FindUID(WPFJM.ServiceReference1.FindUIDRequest request) {
            return base.Channel.FindUID(request);
        }
        
        public WPFJM.ServiceReference1.User FindUID(string searchstring) {
            WPFJM.ServiceReference1.FindUIDRequest inValue = new WPFJM.ServiceReference1.FindUIDRequest();
            inValue.Body = new WPFJM.ServiceReference1.FindUIDRequestBody();
            inValue.Body.searchstring = searchstring;
            WPFJM.ServiceReference1.FindUIDResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).FindUID(inValue);
            return retVal.Body.FindUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.InsertDeviceDetailsResponse WPFJM.ServiceReference1.Service1Soap.InsertDeviceDetails(WPFJM.ServiceReference1.InsertDeviceDetailsRequest request) {
            return base.Channel.InsertDeviceDetails(request);
        }
        
        public void InsertDeviceDetails(int DID, string Dname, string Dintroduction, int Dappearance) {
            WPFJM.ServiceReference1.InsertDeviceDetailsRequest inValue = new WPFJM.ServiceReference1.InsertDeviceDetailsRequest();
            inValue.Body = new WPFJM.ServiceReference1.InsertDeviceDetailsRequestBody();
            inValue.Body.DID = DID;
            inValue.Body.Dname = Dname;
            inValue.Body.Dintroduction = Dintroduction;
            inValue.Body.Dappearance = Dappearance;
            WPFJM.ServiceReference1.InsertDeviceDetailsResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).InsertDeviceDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.FindDeviceResponse WPFJM.ServiceReference1.Service1Soap.FindDevice(WPFJM.ServiceReference1.FindDeviceRequest request) {
            return base.Channel.FindDevice(request);
        }
        
        public WPFJM.ServiceReference1.Device[] FindDevice(string searchstring) {
            WPFJM.ServiceReference1.FindDeviceRequest inValue = new WPFJM.ServiceReference1.FindDeviceRequest();
            inValue.Body = new WPFJM.ServiceReference1.FindDeviceRequestBody();
            inValue.Body.searchstring = searchstring;
            WPFJM.ServiceReference1.FindDeviceResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).FindDevice(inValue);
            return retVal.Body.FindDeviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.GetAllDeviceResponse WPFJM.ServiceReference1.Service1Soap.GetAllDevice(WPFJM.ServiceReference1.GetAllDeviceRequest request) {
            return base.Channel.GetAllDevice(request);
        }
        
        public WPFJM.ServiceReference1.Device[] GetAllDevice() {
            WPFJM.ServiceReference1.GetAllDeviceRequest inValue = new WPFJM.ServiceReference1.GetAllDeviceRequest();
            inValue.Body = new WPFJM.ServiceReference1.GetAllDeviceRequestBody();
            WPFJM.ServiceReference1.GetAllDeviceResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).GetAllDevice(inValue);
            return retVal.Body.GetAllDeviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.FindChatByUIDResponse WPFJM.ServiceReference1.Service1Soap.FindChatByUID(WPFJM.ServiceReference1.FindChatByUIDRequest request) {
            return base.Channel.FindChatByUID(request);
        }
        
        public WPFJM.ServiceReference1.Chat[] FindChatByUID(string searchstring) {
            WPFJM.ServiceReference1.FindChatByUIDRequest inValue = new WPFJM.ServiceReference1.FindChatByUIDRequest();
            inValue.Body = new WPFJM.ServiceReference1.FindChatByUIDRequestBody();
            inValue.Body.searchstring = searchstring;
            WPFJM.ServiceReference1.FindChatByUIDResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).FindChatByUID(inValue);
            return retVal.Body.FindChatByUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.FindChatByDIDResponse WPFJM.ServiceReference1.Service1Soap.FindChatByDID(WPFJM.ServiceReference1.FindChatByDIDRequest request) {
            return base.Channel.FindChatByDID(request);
        }
        
        public WPFJM.ServiceReference1.Chat[] FindChatByDID(string searchstring) {
            WPFJM.ServiceReference1.FindChatByDIDRequest inValue = new WPFJM.ServiceReference1.FindChatByDIDRequest();
            inValue.Body = new WPFJM.ServiceReference1.FindChatByDIDRequestBody();
            inValue.Body.searchstring = searchstring;
            WPFJM.ServiceReference1.FindChatByDIDResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).FindChatByDID(inValue);
            return retVal.Body.FindChatByDIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.InsertChatDetailsResponse WPFJM.ServiceReference1.Service1Soap.InsertChatDetails(WPFJM.ServiceReference1.InsertChatDetailsRequest request) {
            return base.Channel.InsertChatDetails(request);
        }
        
        public void InsertChatDetails(int ChatID, int DID, int UID, string Comment) {
            WPFJM.ServiceReference1.InsertChatDetailsRequest inValue = new WPFJM.ServiceReference1.InsertChatDetailsRequest();
            inValue.Body = new WPFJM.ServiceReference1.InsertChatDetailsRequestBody();
            inValue.Body.ChatID = ChatID;
            inValue.Body.DID = DID;
            inValue.Body.UID = UID;
            inValue.Body.Comment = Comment;
            WPFJM.ServiceReference1.InsertChatDetailsResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).InsertChatDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFJM.ServiceReference1.GetAllChatResponse WPFJM.ServiceReference1.Service1Soap.GetAllChat(WPFJM.ServiceReference1.GetAllChatRequest request) {
            return base.Channel.GetAllChat(request);
        }
        
        public WPFJM.ServiceReference1.Chat[] GetAllChat() {
            WPFJM.ServiceReference1.GetAllChatRequest inValue = new WPFJM.ServiceReference1.GetAllChatRequest();
            inValue.Body = new WPFJM.ServiceReference1.GetAllChatRequestBody();
            WPFJM.ServiceReference1.GetAllChatResponse retVal = ((WPFJM.ServiceReference1.Service1Soap)(this)).GetAllChat(inValue);
            return retVal.Body.GetAllChatResult;
        }
    }
}
